from __future__ import annotations

from .contracts import (
    AgentIntegration,
    DeliveryRetryDecision,
    MCPServerFactory,
    NoopAgentIntegration,
)
from .hooks import (
    annotate_integration_history_events,
    build_integration_history_prompt,
    build_integration_system_prompt,
    clear_integration_chat_contexts,
    clear_terminal_alert_integration_tools,
    ensure_integration_chat_context_tools,
    ensure_terminal_alert_integration_tools,
    extract_integration_context_targets,
    fallback_is_delivery_result,
    get_builtin_mcp_server_factory,
    get_builtin_skill_definitions,
    get_delivery_retry_decision,
    inject_integration_tool_args,
    integration_fallback_response_content,
    integration_history_event_matches_scopes,
    integration_message_sent,
    record_integration_context_targets,
    record_integration_delivery_correction,
    record_integration_no_final_response,
    send_integration_final_response_fallback,
    setup_integration_chat_contexts,
    should_enable_terminal_alert_integrations,
)
from .registry import (
    get_agent_integration,
    get_agent_integrations,
    load_agent_integrations,
    register_agent_integration,
    reload_agent_integrations,
)

__all__ = [
    "AgentIntegration",
    "DeliveryRetryDecision",
    "MCPServerFactory",
    "NoopAgentIntegration",
    "annotate_integration_history_events",
    "build_integration_history_prompt",
    "build_integration_system_prompt",
    "clear_integration_chat_contexts",
    "clear_terminal_alert_integration_tools",
    "ensure_integration_chat_context_tools",
    "ensure_terminal_alert_integration_tools",
    "extract_integration_context_targets",
    "fallback_is_delivery_result",
    "get_agent_integration",
    "get_agent_integrations",
    "get_builtin_mcp_server_factory",
    "get_builtin_skill_definitions",
    "get_delivery_retry_decision",
    "inject_integration_tool_args",
    "integration_fallback_response_content",
    "integration_history_event_matches_scopes",
    "integration_message_sent",
    "load_agent_integrations",
    "record_integration_context_targets",
    "record_integration_delivery_correction",
    "record_integration_no_final_response",
    "register_agent_integration",
    "reload_agent_integrations",
    "send_integration_final_response_fallback",
    "setup_integration_chat_contexts",
    "should_enable_terminal_alert_integrations",
]
