// This file is auto-generated by @hey-api/openapi-ts

export const AddItemToHandlerRequestSchema = {
    properties: {
        item_handler_id: {
            type: 'string',
            format: 'uuid',
            title: 'Item Handler Id'
        },
        item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Item Id'
        }
    },
    type: 'object',
    required: ['item_handler_id', 'item_id'],
    title: 'AddItemToHandlerRequest'
} as const;

export const AddUserToHandlerRequestSchema = {
    properties: {
        item_handler_id: {
            type: 'string',
            format: 'uuid',
            title: 'Item Handler Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['item_handler_id', 'user_id'],
    title: 'AddUserToHandlerRequest'
} as const;

export const Body_items_disconnect_item_subscriberSchema = {
    properties: {
        user_uuid: {
            type: 'string',
            title: 'User Uuid'
        },
        ip_address: {
            type: 'string',
            title: 'Ip Address'
        }
    },
    type: 'object',
    title: 'Body_items-disconnect_item_subscriber'
} as const;

export const Body_items_test_input_filterSchema = {
    properties: {
        test_text: {
            type: 'string',
            title: 'Test Text'
        }
    },
    type: 'object',
    required: ['test_text'],
    title: 'Body_items-test_input_filter'
} as const;

export const Body_items_test_output_filterSchema = {
    properties: {
        command: {
            type: 'string',
            title: 'Command'
        }
    },
    type: 'object',
    required: ['command'],
    title: 'Body_items-test_output_filter'
} as const;

export const Body_items_verify_terminal_tokenSchema = {
    properties: {
        temp_token: {
            type: 'string',
            title: 'Temp Token'
        },
        item_uuid: {
            type: 'string',
            title: 'Item Uuid'
        }
    },
    type: 'object',
    required: ['temp_token', 'item_uuid'],
    title: 'Body_items-verify_terminal_token'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_skills_create_skill_fileSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content',
            default: ''
        }
    },
    type: 'object',
    title: 'Body_skills-create_skill_file'
} as const;

export const Body_skills_update_skill_fileSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'Body_skills-update_skill_file'
} as const;

export const Body_skills_upload_skill_zipSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_skills-upload_skill_zip'
} as const;

export const ChatMessageSchema = {
    properties: {
        role: {
            type: 'string',
            title: 'Role'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['role', 'content'],
    title: 'ChatMessage'
} as const;

export const ChatRequestSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        history: {
            items: {
                '$ref': '#/components/schemas/ChatMessage'
            },
            type: 'array',
            title: 'History',
            default: []
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ChatRequest'
} as const;

export const ChatStreamRequestSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        history: {
            items: {
                '$ref': '#/components/schemas/ChatMessage'
            },
            type: 'array',
            title: 'History',
            default: []
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ChatStreamRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        status: {
            '$ref': '#/components/schemas/ItemStatus',
            default: 'stopped'
        },
        log_max_size_mb: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 1000,
                    minimum: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Log Max Size Mb',
            default: 100
        },
        socket_host: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Host',
            default: 'localhost'
        },
        socket_port: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 65535,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Port',
            default: 9000
        },
        socket_connected: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Connected',
            default: false
        },
        socket_last_connected: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Last Connected'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        command: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        working_directory: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Working Directory'
        },
        input_filter_enabled: {
            type: 'boolean',
            title: 'Input Filter Enabled',
            default: false
        },
        input_filter_rules: {
            additionalProperties: true,
            type: 'object',
            title: 'Input Filter Rules'
        },
        output_filter_enabled: {
            type: 'boolean',
            title: 'Output Filter Enabled',
            default: false
        },
        output_filter_rules: {
            additionalProperties: true,
            type: 'object',
            title: 'Output Filter Rules'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'owner_id'],
    title: 'Item'
} as const;

export const ItemChatSessionPublicSchema = {
    properties: {
        messages: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Messages'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Item Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'item_id'],
    title: 'ItemChatSessionPublic'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        status: {
            '$ref': '#/components/schemas/ItemStatus',
            default: 'stopped'
        },
        log_max_size_mb: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 1000,
                    minimum: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Log Max Size Mb',
            default: 100
        },
        socket_host: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Host',
            default: 'localhost'
        },
        socket_port: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 65535,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Port',
            default: 9000
        },
        socket_connected: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Connected',
            default: false
        },
        socket_last_connected: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Last Connected'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        command: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        working_directory: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Working Directory'
        },
        input_filter_enabled: {
            type: 'boolean',
            title: 'Input Filter Enabled',
            default: false
        },
        input_filter_rules: {
            additionalProperties: true,
            type: 'object',
            title: 'Input Filter Rules'
        },
        output_filter_enabled: {
            type: 'boolean',
            title: 'Output Filter Enabled',
            default: false
        },
        output_filter_rules: {
            additionalProperties: true,
            type: 'object',
            title: 'Output Filter Rules'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemHandlerSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        model: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        api_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Url'
        },
        enabled_skills: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled Skills'
        },
        enabled_mcp_servers: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled Mcp Servers'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['name', 'owner_id'],
    title: 'ItemHandler'
} as const;

export const ItemHandlerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        model: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        api_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Url'
        },
        enabled_skills: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled Skills'
        },
        enabled_mcp_servers: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled Mcp Servers'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ItemHandlerCreate'
} as const;

export const ItemHandlerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        model: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        api_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Url'
        },
        enabled_skills: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled Skills'
        },
        enabled_mcp_servers: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled Mcp Servers'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id'],
    title: 'ItemHandlerPublic'
} as const;

export const ItemHandlerUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        model: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        api_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Url'
        },
        enabled_skills: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled Skills'
        },
        enabled_mcp_servers: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled Mcp Servers'
        }
    },
    type: 'object',
    title: 'ItemHandlerUpdate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        status: {
            '$ref': '#/components/schemas/ItemStatus',
            default: 'stopped'
        },
        log_max_size_mb: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 1000,
                    minimum: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Log Max Size Mb',
            default: 100
        },
        socket_host: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Host',
            default: 'localhost'
        },
        socket_port: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 65535,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Port',
            default: 9000
        },
        socket_connected: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Connected',
            default: false
        },
        socket_last_connected: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Last Connected'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        command: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        working_directory: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Working Directory'
        },
        input_filter_enabled: {
            type: 'boolean',
            title: 'Input Filter Enabled',
            default: false
        },
        input_filter_rules: {
            additionalProperties: true,
            type: 'object',
            title: 'Input Filter Rules'
        },
        output_filter_enabled: {
            type: 'boolean',
            title: 'Output Filter Enabled',
            default: false
        },
        output_filter_rules: {
            additionalProperties: true,
            type: 'object',
            title: 'Output Filter Rules'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemStatusSchema = {
    type: 'string',
    enum: ['stopped', 'running', 'starting', 'stopping', 'error'],
    title: 'ItemStatus'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ItemStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        log_max_size_mb: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 1000,
                    minimum: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Log Max Size Mb'
        },
        socket_host: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Host'
        },
        socket_port: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 65535,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Port'
        },
        socket_connected: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Connected'
        },
        socket_last_connected: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socket Last Connected'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        command: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        working_directory: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Working Directory'
        },
        input_filter_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Filter Enabled'
        },
        input_filter_rules: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Filter Rules'
        },
        output_filter_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Output Filter Enabled'
        },
        output_filter_rules: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Output Filter Rules'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const MCPServerCreateBodySchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        command: {
            type: 'string',
            title: 'Command'
        },
        args: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Args',
            default: []
        },
        env: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Env',
            default: {}
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        description: {
            type: 'string',
            title: 'Description',
            default: ''
        }
    },
    type: 'object',
    required: ['name', 'command'],
    title: 'MCPServerCreateBody'
} as const;

export const MCPServerItemSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        command: {
            type: 'string',
            title: 'Command'
        },
        args: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Args'
        },
        env: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Env'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'command', 'args', 'env', 'enabled', 'description'],
    title: 'MCPServerItem'
} as const;

export const MCPServerListResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MCPServerItem'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MCPServerListResponse'
} as const;

export const MCPServerUpdateBodySchema = {
    properties: {
        command: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        args: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Args'
        },
        env: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Env'
        },
        enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'MCPServerUpdateBody'
} as const;

export const MemoryCreateSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        memory_type: {
            type: 'string',
            enum: ['fact', 'preference', 'error', 'context'],
            title: 'Memory Type',
            default: 'fact'
        },
        metadata: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata'
        },
        ttl_days: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ttl Days'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'MemoryCreate'
} as const;

export const MemorySearchSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        n_results: {
            type: 'integer',
            title: 'N Results',
            default: 5
        },
        memory_type: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['fact', 'preference', 'error', 'context']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memory Type'
        }
    },
    type: 'object',
    required: ['query'],
    title: 'MemorySearch'
} as const;

export const MemoryUpdateSchema = {
    properties: {
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        metadata: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata'
        }
    },
    type: 'object',
    title: 'MemoryUpdate'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SkillCreateBodySchema = {
    properties: {
        skill_id: {
            type: 'string',
            title: 'Skill Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description',
            default: ''
        },
        category: {
            type: 'string',
            title: 'Category',
            default: 'general'
        }
    },
    type: 'object',
    required: ['skill_id', 'name'],
    title: 'SkillCreateBody'
} as const;

export const SkillDetailSchema = {
    properties: {
        skill_id: {
            type: 'string',
            title: 'Skill Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        trigger: {
            additionalProperties: true,
            type: 'object',
            title: 'Trigger'
        },
        action: {
            additionalProperties: true,
            type: 'object',
            title: 'Action'
        },
        safety: {
            additionalProperties: true,
            type: 'object',
            title: 'Safety'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        scripts: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Scripts'
        },
        templates: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Templates'
        },
        resources: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Resources'
        },
        examples: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Examples'
        }
    },
    type: 'object',
    required: ['skill_id', 'name', 'description', 'category', 'trigger', 'action', 'safety', 'content', 'scripts', 'templates', 'resources', 'examples'],
    title: 'SkillDetail'
} as const;

export const SkillListItemSchema = {
    properties: {
        skill_id: {
            type: 'string',
            title: 'Skill Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        category: {
            type: 'string',
            title: 'Category'
        }
    },
    type: 'object',
    required: ['skill_id', 'name', 'description', 'category'],
    title: 'SkillListItem'
} as const;

export const SkillUpdateBodySchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        trigger: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trigger'
        },
        action: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Action'
        },
        safety: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Safety'
        }
    },
    type: 'object',
    title: 'SkillUpdateBody'
} as const;

export const SkillsListResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SkillListItem'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SkillsListResponse'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        hashed_password: {
            type: 'string',
            title: 'Hashed Password'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'hashed_password'],
    title: 'User'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;
