// This file is auto-generated by @hey-api/openapi-ts

export type AddItemToHandlerRequest = {
    item_handler_id: string;
    item_id: string;
};

export type AddUserToHandlerRequest = {
    item_handler_id: string;
    user_id: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Item = {
    title: string;
    description?: (string | null);
    status?: ItemStatus;
    config?: ({
    [key: string]: unknown;
} | null);
    resource_usage?: ({
    [key: string]: unknown;
} | null);
    log_path?: (string | null);
    log_max_size_mb?: (number | null);
    socket_connection_type?: SocketConnectionType;
    socket_host?: (string | null);
    socket_port?: (number | null);
    socket_connected?: (boolean | null);
    socket_last_connected?: (string | null);
    socket_unique_id?: (string | null);
    api_key?: (string | null);
    command?: (string | null);
    executable_path?: (string | null);
    working_directory?: (string | null);
    id?: string;
    created_at?: string;
    updated_at?: string;
    owner_id: string;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
    status?: ItemStatus;
    config?: ({
    [key: string]: unknown;
} | null);
    resource_usage?: ({
    [key: string]: unknown;
} | null);
    log_path?: (string | null);
    log_max_size_mb?: (number | null);
    socket_connection_type?: SocketConnectionType;
    socket_host?: (string | null);
    socket_port?: (number | null);
    socket_connected?: (boolean | null);
    socket_last_connected?: (string | null);
    socket_unique_id?: (string | null);
    api_key?: (string | null);
    command?: (string | null);
    executable_path?: (string | null);
    working_directory?: (string | null);
};

export type ItemHandler = {
    name: string;
    model?: (string | null);
    api_key?: (string | null);
    api_url?: (string | null);
    id?: string;
    created_at?: string;
    updated_at?: string;
    owner_id: string;
};

export type ItemHandlerCreate = {
    name: string;
    model?: (string | null);
    api_key?: (string | null);
    api_url?: (string | null);
};

export type ItemHandlerPublic = {
    name: string;
    model?: (string | null);
    api_key?: (string | null);
    api_url?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ItemHandlerUpdate = {
    name?: (string | null);
    model?: (string | null);
    api_key?: (string | null);
    api_url?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    status?: ItemStatus;
    config?: ({
    [key: string]: unknown;
} | null);
    resource_usage?: ({
    [key: string]: unknown;
} | null);
    log_path?: (string | null);
    log_max_size_mb?: (number | null);
    socket_connection_type?: SocketConnectionType;
    socket_host?: (string | null);
    socket_port?: (number | null);
    socket_connected?: (boolean | null);
    socket_last_connected?: (string | null);
    socket_unique_id?: (string | null);
    api_key?: (string | null);
    command?: (string | null);
    executable_path?: (string | null);
    working_directory?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemStatus = 'stopped' | 'running' | 'starting' | 'stopping' | 'error';

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
    status?: (ItemStatus | null);
    config?: ({
    [key: string]: unknown;
} | null);
    resource_usage?: ({
    [key: string]: unknown;
} | null);
    log_path?: (string | null);
    log_max_size_mb?: (number | null);
    socket_connection_type?: (SocketConnectionType | null);
    socket_host?: (string | null);
    socket_port?: (number | null);
    socket_connected?: (boolean | null);
    socket_last_connected?: (string | null);
    socket_unique_id?: (string | null);
    api_key?: (string | null);
    command?: (string | null);
    executable_path?: (string | null);
    working_directory?: (string | null);
    command_args?: (Array<unknown> | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SocketConnectionType = 'local' | 'remote';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type User = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id?: string;
    hashed_password: string;
    created_at?: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ItemHandlerAssociationsAddItemToHandlerData = {
    requestBody: AddItemToHandlerRequest;
};

export type ItemHandlerAssociationsAddItemToHandlerResponse = ({
    [key: string]: unknown;
});

export type ItemHandlerAssociationsRemoveItemFromHandlerData = {
    itemHandlerId: string;
    itemId: string;
};

export type ItemHandlerAssociationsRemoveItemFromHandlerResponse = ({
    [key: string]: unknown;
});

export type ItemHandlerAssociationsGetItemsForHandlerData = {
    itemHandlerId: string;
};

export type ItemHandlerAssociationsGetItemsForHandlerResponse = (Array<Item>);

export type ItemHandlerAssociationsGetHandlersForItemData = {
    itemId: string;
};

export type ItemHandlerAssociationsGetHandlersForItemResponse = (Array<ItemHandler>);

export type ItemHandlerAssociationsAddUserToHandlerData = {
    requestBody: AddUserToHandlerRequest;
};

export type ItemHandlerAssociationsAddUserToHandlerResponse = ({
    [key: string]: unknown;
});

export type ItemHandlerAssociationsRemoveUserFromHandlerData = {
    itemHandlerId: string;
    userId: string;
};

export type ItemHandlerAssociationsRemoveUserFromHandlerResponse = ({
    [key: string]: unknown;
});

export type ItemHandlerAssociationsGetUsersForHandlerData = {
    itemHandlerId: string;
};

export type ItemHandlerAssociationsGetUsersForHandlerResponse = (Array<User>);

export type ItemHandlerAssociationsGetHandlersForUserData = {
    userId: string;
};

export type ItemHandlerAssociationsGetHandlersForUserResponse = (Array<ItemHandler>);

export type ItemHandlersReadItemHandlersData = {
    limit?: number;
    skip?: number;
};

export type ItemHandlersReadItemHandlersResponse = (Array<ItemHandlerPublic>);

export type ItemHandlersCreateItemHandlerData = {
    requestBody: ItemHandlerCreate;
};

export type ItemHandlersCreateItemHandlerResponse = (ItemHandlerPublic);

export type ItemHandlersReadItemHandlerData = {
    id: string;
};

export type ItemHandlersReadItemHandlerResponse = (ItemHandlerPublic);

export type ItemHandlersUpdateItemHandlerData = {
    id: string;
    requestBody: ItemHandlerUpdate;
};

export type ItemHandlersUpdateItemHandlerResponse = (ItemHandlerPublic);

export type ItemHandlersDeleteItemHandlerData = {
    id: string;
};

export type ItemHandlersDeleteItemHandlerResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);