// This file is auto-generated by @hey-api/openapi-ts

export type AddItemToHandlerRequest = {
    item_handler_id: string;
    item_id: string;
};

export type AddUserToHandlerRequest = {
    item_handler_id: string;
    user_id: string;
};

export type Body_items_disconnect_item_subscriber = {
    user_uuid?: string;
    ip_address?: string;
};

export type Body_items_test_input_filter = {
    test_text: string;
};

export type Body_items_test_output_filter = {
    command: string;
};

export type Body_items_verify_terminal_token = {
    temp_token: string;
    item_uuid: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_skills_create_skill_file = {
    content?: string;
};

export type Body_skills_update_skill_file = {
    content: string;
};

export type Body_skills_upload_skill_zip = {
    file: string;
};

export type ChatMessage = {
    role: string;
    content: string;
};

export type ChatRequest = {
    message: string;
    history?: Array<ChatMessage>;
};

export type ChatStreamRequest = {
    message: string;
    history?: Array<ChatMessage>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Item = {
    title: string;
    description?: (string | null);
    status?: ItemStatus;
    log_max_size_mb?: (number | null);
    socket_host?: (string | null);
    socket_port?: (number | null);
    socket_connected?: (boolean | null);
    socket_last_connected?: (string | null);
    api_key?: (string | null);
    command?: (string | null);
    working_directory?: (string | null);
    input_filter_enabled?: boolean;
    input_filter_rules?: {
        [key: string]: unknown;
    };
    output_filter_enabled?: boolean;
    output_filter_rules?: {
        [key: string]: unknown;
    };
    id?: string;
    created_at?: string;
    updated_at?: string;
    owner_id: string;
};

export type ItemChatSessionPublic = {
    messages?: Array<{
        [key: string]: unknown;
    }>;
    id: string;
    item_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
    status?: ItemStatus;
    log_max_size_mb?: (number | null);
    socket_host?: (string | null);
    socket_port?: (number | null);
    socket_connected?: (boolean | null);
    socket_last_connected?: (string | null);
    api_key?: (string | null);
    command?: (string | null);
    working_directory?: (string | null);
    input_filter_enabled?: boolean;
    input_filter_rules?: {
        [key: string]: unknown;
    };
    output_filter_enabled?: boolean;
    output_filter_rules?: {
        [key: string]: unknown;
    };
};

export type ItemHandler = {
    name: string;
    model?: (string | null);
    api_key?: (string | null);
    api_url?: (string | null);
    enabled_skills?: (Array<(string)> | null);
    enabled_mcp_servers?: (Array<(string)> | null);
    id?: string;
    created_at?: string;
    updated_at?: string;
    owner_id: string;
};

export type ItemHandlerCreate = {
    name: string;
    model?: (string | null);
    api_key?: (string | null);
    api_url?: (string | null);
    enabled_skills?: (Array<(string)> | null);
    enabled_mcp_servers?: (Array<(string)> | null);
};

export type ItemHandlerPublic = {
    name: string;
    model?: (string | null);
    api_url?: (string | null);
    enabled_skills?: (Array<(string)> | null);
    enabled_mcp_servers?: (Array<(string)> | null);
    enabled_knowledge_files?: (Array<(string)> | null);
    agent_profile?: {
        [key: string]: unknown;
    };
    has_api_key?: boolean;
    id: string;
    owner_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ItemHandlerUpdate = {
    name?: (string | null);
    model?: (string | null);
    api_key?: (string | null);
    api_url?: (string | null);
    enabled_skills?: (Array<(string)> | null);
    enabled_mcp_servers?: (Array<(string)> | null);
    enabled_knowledge_files?: (Array<(string)> | null);
    agent_profile?: ({
        [key: string]: unknown;
    } | null);
    clear_api_key?: boolean;
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    status?: ItemStatus;
    log_max_size_mb?: (number | null);
    socket_host?: (string | null);
    socket_port?: (number | null);
    socket_connected?: (boolean | null);
    socket_last_connected?: (string | null);
    api_key?: (string | null);
    command?: (string | null);
    working_directory?: (string | null);
    input_filter_enabled?: boolean;
    input_filter_rules?: {
        [key: string]: unknown;
    };
    output_filter_enabled?: boolean;
    output_filter_rules?: {
        [key: string]: unknown;
    };
    id: string;
    owner_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ItemStatus = 'stopped' | 'running' | 'starting' | 'stopping' | 'error';

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
    status?: (ItemStatus | null);
    log_max_size_mb?: (number | null);
    socket_host?: (string | null);
    socket_port?: (number | null);
    socket_connected?: (boolean | null);
    socket_last_connected?: (string | null);
    api_key?: (string | null);
    command?: (string | null);
    working_directory?: (string | null);
    input_filter_enabled?: (boolean | null);
    input_filter_rules?: ({
    [key: string]: unknown;
} | null);
    output_filter_enabled?: (boolean | null);
    output_filter_rules?: ({
    [key: string]: unknown;
} | null);
};

export type MCPServerCreateBody = {
    name: string;
    command: string;
    args?: Array<(string)>;
    env?: {
        [key: string]: (string);
    };
    enabled?: boolean;
    description?: string;
};

export type MCPServerItem = {
    name: string;
    command: string;
    args: Array<(string)>;
    env: {
        [key: string]: (string);
    };
    enabled: boolean;
    description: string;
};

export type MCPServerListResponse = {
    data: Array<MCPServerItem>;
    count: number;
};

export type MCPServerUpdateBody = {
    command?: (string | null);
    args?: (Array<(string)> | null);
    env?: ({
    [key: string]: (string);
} | null);
    enabled?: (boolean | null);
    description?: (string | null);
};

export type MemoryCreate = {
    content: string;
    memory_type?: 'fact' | 'preference' | 'task' | 'error' | 'context';
    metadata?: ({
    [key: string]: unknown;
} | null);
    ttl_days?: (number | null);
};

export type memory_type = 'fact' | 'preference' | 'task' | 'error' | 'context';

export type MemorySearch = {
    query: string;
    n_results?: number;
    memory_type?: ('fact' | 'preference' | 'task' | 'error' | 'context' | null);
};

export type MemoryUpdate = {
    content?: (string | null);
    metadata?: ({
    [key: string]: unknown;
} | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SkillCreateBody = {
    skill_id: string;
    name: string;
    description?: string;
    category?: string;
};

export type SkillDetail = {
    skill_id: string;
    name: string;
    description: string;
    category: string;
    trigger: {
        [key: string]: unknown;
    };
    action: {
        [key: string]: unknown;
    };
    safety: {
        [key: string]: unknown;
    };
    content: string;
    scripts: Array<(string)>;
    templates: Array<(string)>;
    resources: Array<(string)>;
    examples: Array<{
        [key: string]: unknown;
    }>;
};

export type SkillListItem = {
    skill_id: string;
    name: string;
    description: string;
    category: string;
};

export type SkillsListResponse = {
    data: Array<SkillListItem>;
    count: number;
};

export type SkillUpdateBody = {
    name?: (string | null);
    description?: (string | null);
    category?: (string | null);
    trigger?: ({
    [key: string]: unknown;
} | null);
    action?: ({
    [key: string]: unknown;
} | null);
    safety?: ({
    [key: string]: unknown;
} | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type User = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id?: string;
    hashed_password: string;
    created_at?: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ChatChatData = {
    itemId: string;
    requestBody: ChatRequest;
};

export type ChatChatResponse = ({
    [key: string]: unknown;
});

export type ChatChatStreamData = {
    itemId: string;
    requestBody: ChatStreamRequest;
};

export type ChatChatStreamResponse = (unknown);

export type ChatGetMatchedSkillsData = {
    itemId: string;
    query: string;
};

export type ChatGetMatchedSkillsResponse = (unknown);

export type ChatAgentEventsData = {
    itemId: string;
};

export type ChatAgentEventsResponse = (unknown);

export type ChatAbortChatData = {
    itemId: string;
};

export type ChatAbortChatResponse = (unknown);

export type ItemHandlerAssociationsAddItemToHandlerData = {
    requestBody: AddItemToHandlerRequest;
};

export type ItemHandlerAssociationsAddItemToHandlerResponse = ({
    [key: string]: unknown;
});

export type ItemHandlerAssociationsRemoveItemFromHandlerData = {
    itemHandlerId: string;
    itemId: string;
};

export type ItemHandlerAssociationsRemoveItemFromHandlerResponse = ({
    [key: string]: unknown;
});

export type ItemHandlerAssociationsGetItemsForHandlerData = {
    itemHandlerId: string;
};

export type ItemHandlerAssociationsGetItemsForHandlerResponse = (Array<Item>);

export type ItemHandlerAssociationsGetHandlersForItemData = {
    itemId: string;
};

export type ItemHandlerAssociationsGetHandlersForItemResponse = (Array<ItemHandler>);

export type ItemHandlerAssociationsAddUserToHandlerData = {
    requestBody: AddUserToHandlerRequest;
};

export type ItemHandlerAssociationsAddUserToHandlerResponse = ({
    [key: string]: unknown;
});

export type ItemHandlerAssociationsRemoveUserFromHandlerData = {
    itemHandlerId: string;
    userId: string;
};

export type ItemHandlerAssociationsRemoveUserFromHandlerResponse = ({
    [key: string]: unknown;
});

export type ItemHandlerAssociationsGetUsersForHandlerData = {
    itemHandlerId: string;
};

export type ItemHandlerAssociationsGetUsersForHandlerResponse = (Array<User>);

export type ItemHandlerAssociationsGetHandlersForUserData = {
    userId: string;
};

export type ItemHandlerAssociationsGetHandlersForUserResponse = (Array<ItemHandler>);

export type ItemHandlersReadItemHandlersData = {
    limit?: number;
    skip?: number;
};

export type ItemHandlersReadItemHandlersResponse = (Array<ItemHandlerPublic>);

export type ItemHandlersCreateItemHandlerData = {
    requestBody: ItemHandlerCreate;
};

export type ItemHandlersCreateItemHandlerResponse = (ItemHandlerPublic);

export type ItemHandlersReadItemHandlerData = {
    id: string;
};

export type ItemHandlersReadItemHandlerResponse = (ItemHandlerPublic);

export type ItemHandlersUpdateItemHandlerData = {
    id: string;
    requestBody: ItemHandlerUpdate;
};

export type ItemHandlersUpdateItemHandlerResponse = (ItemHandlerPublic);

export type ItemHandlersDeleteItemHandlerData = {
    id: string;
};

export type ItemHandlersDeleteItemHandlerResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = ({
    [key: string]: unknown;
});

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = ({
    [key: string]: unknown;
});

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type ItemsReconnectDaemonData = {
    daemonId: string;
};

export type ItemsReconnectDaemonResponse = (unknown);

export type ItemsStartItemData = {
    id: string;
};

export type ItemsStartItemResponse = (Message);

export type ItemsStopItemData = {
    id: string;
};

export type ItemsStopItemResponse = (Message);

export type ItemsRestartItemData = {
    id: string;
};

export type ItemsRestartItemResponse = (Message);

export type ItemsGetTerminalTokenData = {
    id: string;
};

export type ItemsGetTerminalTokenResponse = ({
    [key: string]: unknown;
});

export type ItemsVerifyTerminalTokenData = {
    id: string;
    requestBody: Body_items_verify_terminal_token;
};

export type ItemsVerifyTerminalTokenResponse = ({
    [key: string]: unknown;
});

export type ItemsGetItemSubscribersData = {
    id: string;
};

export type ItemsGetItemSubscribersResponse = ({
    [key: string]: unknown;
});

export type ItemsDisconnectItemSubscriberData = {
    id: string;
    requestBody?: Body_items_disconnect_item_subscriber;
};

export type ItemsDisconnectItemSubscriberResponse = ({
    [key: string]: unknown;
});

export type ItemsGetItemOutputData = {
    id: string;
    lines?: number;
};

export type ItemsGetItemOutputResponse = ({
    [key: string]: unknown;
});

export type ItemsTestInputFilterData = {
    id: string;
    requestBody: Body_items_test_input_filter;
};

export type ItemsTestInputFilterResponse = ({
    [key: string]: unknown;
});

export type ItemsTestOutputFilterData = {
    id: string;
    requestBody: Body_items_test_output_filter;
};

export type ItemsTestOutputFilterResponse = ({
    [key: string]: unknown;
});

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type McpListMcpServersResponse = (MCPServerListResponse);

export type McpCreateMcpServerData = {
    requestBody: MCPServerCreateBody;
};

export type McpCreateMcpServerResponse = (MCPServerItem);

export type McpGetMcpServerData = {
    serverName: string;
};

export type McpGetMcpServerResponse = (MCPServerItem);

export type McpUpdateMcpServerData = {
    requestBody: MCPServerUpdateBody;
    serverName: string;
};

export type McpUpdateMcpServerResponse = (MCPServerItem);

export type McpDeleteMcpServerData = {
    serverName: string;
};

export type McpDeleteMcpServerResponse = (unknown);

export type McpReloadMcpServersResponse = (unknown);

export type MemoryGetChatSessionData = {
    itemId: string;
};

export type MemoryGetChatSessionResponse = (ItemChatSessionPublic);

export type MemorySaveChatSessionData = {
    itemId: string;
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type MemorySaveChatSessionResponse = (ItemChatSessionPublic);

export type MemoryClearChatSessionData = {
    itemId: string;
};

export type MemoryClearChatSessionResponse = (unknown);

export type MemoryClearAllSessionDataData = {
    itemId: string;
};

export type MemoryClearAllSessionDataResponse = (unknown);

export type MemoryGetAllMemoriesData = {
    itemId: string;
    memoryType?: ('fact' | 'preference' | 'task' | 'error' | 'context' | null);
};

export type MemoryGetAllMemoriesResponse = (unknown);

export type MemoryAddMemoryData = {
    itemId: string;
    requestBody: MemoryCreate;
};

export type MemoryAddMemoryResponse = (unknown);

export type MemoryClearMemoriesData = {
    itemId: string;
};

export type MemoryClearMemoriesResponse = (unknown);

export type MemoryGetMemoryStatsData = {
    itemId: string;
};

export type MemoryGetMemoryStatsResponse = (unknown);

export type MemoryGetMemoryTypesResponse = (unknown);

export type MemorySearchMemoriesData = {
    itemId: string;
    requestBody: MemorySearch;
};

export type MemorySearchMemoriesResponse = (unknown);

export type MemoryUpdateMemoryData = {
    itemId: string;
    memoryId: string;
    requestBody: MemoryUpdate;
};

export type MemoryUpdateMemoryResponse = (unknown);

export type MemoryDeleteMemoryData = {
    itemId: string;
    memoryId: string;
};

export type MemoryDeleteMemoryResponse = (unknown);

export type MemoryExpireMemoriesData = {
    itemId: string;
};

export type MemoryExpireMemoriesResponse = (unknown);

export type MemoryDeduplicateMemoriesData = {
    itemId: string;
};

export type MemoryDeduplicateMemoriesResponse = (unknown);

export type MemorySummarizeMemoriesData = {
    itemId: string;
    threshold?: number;
};

export type MemorySummarizeMemoriesResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SkillsListSkillsData = {
    category?: (string | null);
};

export type SkillsListSkillsResponse = (SkillsListResponse);

export type SkillsCreateSkillData = {
    requestBody: SkillCreateBody;
};

export type SkillsCreateSkillResponse = (SkillListItem);

export type SkillsGetSkillData = {
    skillId: string;
};

export type SkillsGetSkillResponse = (SkillDetail);

export type SkillsUpdateSkillData = {
    requestBody: SkillUpdateBody;
    skillId: string;
};

export type SkillsUpdateSkillResponse = (SkillListItem);

export type SkillsDeleteSkillData = {
    skillId: string;
};

export type SkillsDeleteSkillResponse = (unknown);

export type SkillsListSkillFilesData = {
    skillId: string;
};

export type SkillsListSkillFilesResponse = (unknown);

export type SkillsGetSkillFileData = {
    filePath: string;
    skillId: string;
};

export type SkillsGetSkillFileResponse = (unknown);

export type SkillsUpdateSkillFileData = {
    filePath: string;
    requestBody: Body_skills_update_skill_file;
    skillId: string;
};

export type SkillsUpdateSkillFileResponse = (unknown);

export type SkillsCreateSkillFileData = {
    filePath: string;
    requestBody?: Body_skills_create_skill_file;
    skillId: string;
};

export type SkillsCreateSkillFileResponse = (unknown);

export type SkillsDeleteSkillFileData = {
    filePath: string;
    skillId: string;
};

export type SkillsDeleteSkillFileResponse = (unknown);

export type SkillsUploadSkillZipData = {
    formData: Body_skills_upload_skill_zip;
};

export type SkillsUploadSkillZipResponse = (unknown);

export type SkillsReloadSkillsResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);
