"""Initial migration

Revision ID: 90a9ee9fcf5a
Revises: 
Create Date: 2026-03-03 16:55:57.251116

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from app.models import SQLiteUUID



# revision identifiers, used by Alembic.
revision = '90a9ee9fcf5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('resource_usage', sa.JSON(), nullable=True),
    sa.Column('log_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', SQLiteUUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemhandler',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('api_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', SQLiteUUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemhandleritem',
    sa.Column('item_handler_id', SQLiteUUID(), nullable=False),
    sa.Column('item_id', SQLiteUUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_handler_id'], ['itemhandler.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_handler_id', 'item_id')
    )
    op.create_table('itemhandleruser',
    sa.Column('item_handler_id', SQLiteUUID(), nullable=False),
    sa.Column('user_id', SQLiteUUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_handler_id'], ['itemhandler.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_handler_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemhandleruser')
    op.drop_table('itemhandleritem')
    op.drop_table('itemhandler')
    op.drop_table('item')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
