"""Initial migration

Revision ID: a2d5ef82bd0b
Revises: 
Create Date: 2026-03-26 14:40:37.222850

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from app.models import SQLiteUUID


# revision identifiers, used by Alembic.
revision = 'a2d5ef82bd0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', SQLiteUUID, nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('stopped', 'running', 'starting', 'stopping', 'error', name='itemstatus'), nullable=False),
    sa.Column('log_max_size_mb', sa.Integer(), nullable=True),
    sa.Column('socket_host', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('socket_port', sa.Integer(), nullable=True),
    sa.Column('socket_connected', sa.Boolean(), nullable=True),
    sa.Column('socket_last_connected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('working_directory', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('input_filter_enabled', sa.Boolean(), nullable=False),
    sa.Column('input_filter_rules', sa.JSON(), nullable=False),
    sa.Column('output_filter_enabled', sa.Boolean(), nullable=False),
    sa.Column('output_filter_rules', sa.JSON(), nullable=False),
    sa.Column('id', SQLiteUUID, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', SQLiteUUID, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_owner_id'), 'item', ['owner_id'], unique=False)
    op.create_table('itemhandler',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('api_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('enabled_skills', sa.JSON(), nullable=True),
    sa.Column('id', SQLiteUUID, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', SQLiteUUID, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemhandler_owner_id'), 'itemhandler', ['owner_id'], unique=False)
    op.create_table('itemhandleritem',
    sa.Column('item_handler_id', SQLiteUUID, nullable=False),
    sa.Column('item_id', SQLiteUUID, nullable=False),
    sa.ForeignKeyConstraint(['item_handler_id'], ['itemhandler.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_handler_id', 'item_id')
    )
    op.create_index(op.f('ix_itemhandleritem_item_handler_id'), 'itemhandleritem', ['item_handler_id'], unique=False)
    op.create_index(op.f('ix_itemhandleritem_item_id'), 'itemhandleritem', ['item_id'], unique=False)
    op.create_table('itemhandleruser',
    sa.Column('item_handler_id', SQLiteUUID, nullable=False),
    sa.Column('user_id', SQLiteUUID, nullable=False),
    sa.ForeignKeyConstraint(['item_handler_id'], ['itemhandler.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_handler_id', 'user_id')
    )
    op.create_index(op.f('ix_itemhandleruser_item_handler_id'), 'itemhandleruser', ['item_handler_id'], unique=False)
    op.create_index(op.f('ix_itemhandleruser_user_id'), 'itemhandleruser', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itemhandleruser_user_id'), table_name='itemhandleruser')
    op.drop_index(op.f('ix_itemhandleruser_item_handler_id'), table_name='itemhandleruser')
    op.drop_table('itemhandleruser')
    op.drop_index(op.f('ix_itemhandleritem_item_id'), table_name='itemhandleritem')
    op.drop_index(op.f('ix_itemhandleritem_item_handler_id'), table_name='itemhandleritem')
    op.drop_table('itemhandleritem')
    op.drop_index(op.f('ix_itemhandler_owner_id'), table_name='itemhandler')
    op.drop_table('itemhandler')
    op.drop_index(op.f('ix_item_owner_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
