"""Initial migration

Revision ID: dc16467db813
Revises:
Create Date: 2026-04-15 15:35:22.933406

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

from app.models import SQLiteUUID

# revision identifiers, used by Alembic.
revision = 'dc16467db813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('stopped', 'running', 'starting', 'stopping', 'error', name='itemstatus'), nullable=False),
    sa.Column('log_max_size_mb', sa.Integer(), nullable=True),
    sa.Column('socket_host', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('socket_port', sa.Integer(), nullable=True),
    sa.Column('socket_connected', sa.Boolean(), nullable=True),
    sa.Column('socket_last_connected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('working_directory', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('input_filter_enabled', sa.Boolean(), nullable=False),
    sa.Column('input_filter_rules', sa.JSON(), nullable=False),
    sa.Column('output_filter_enabled', sa.Boolean(), nullable=False),
    sa.Column('output_filter_rules', sa.JSON(), nullable=False),
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', SQLiteUUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_owner_id'), 'item', ['owner_id'], unique=False)
    op.create_table('itemhandler',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('api_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('enabled_skills', sa.JSON(), nullable=True),
    sa.Column('enabled_mcp_servers', sa.JSON(), nullable=True),
    sa.Column('enabled_knowledge_files', sa.JSON(), nullable=True),
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', SQLiteUUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemhandler_owner_id'), 'itemhandler', ['owner_id'], unique=False)
    op.create_table('robot',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('protocol', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('app_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('app_secret', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('bot_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('use_websocket', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', SQLiteUUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_owner_id'), 'robot', ['owner_id'], unique=False)
    op.create_table('itemchatsession',
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('item_id', SQLiteUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemchatsession_item_id'), 'itemchatsession', ['item_id'], unique=False)
    op.create_table('itemhandleritem',
    sa.Column('item_handler_id', SQLiteUUID(), nullable=False),
    sa.Column('item_id', SQLiteUUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_handler_id'], ['itemhandler.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_handler_id', 'item_id')
    )
    op.create_index(op.f('ix_itemhandleritem_item_handler_id'), 'itemhandleritem', ['item_handler_id'], unique=False)
    op.create_index(op.f('ix_itemhandleritem_item_id'), 'itemhandleritem', ['item_id'], unique=False)
    op.create_table('itemhandleruser',
    sa.Column('item_handler_id', SQLiteUUID(), nullable=False),
    sa.Column('user_id', SQLiteUUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_handler_id'], ['itemhandler.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_handler_id', 'user_id')
    )
    op.create_index(op.f('ix_itemhandleruser_item_handler_id'), 'itemhandleruser', ['item_handler_id'], unique=False)
    op.create_index(op.f('ix_itemhandleruser_user_id'), 'itemhandleruser', ['user_id'], unique=False)
    op.create_table('robotitem',
    sa.Column('robot_id', SQLiteUUID(), nullable=False),
    sa.Column('item_id', SQLiteUUID(), nullable=False),
    sa.Column('allow_chat', sa.Boolean(), nullable=False),
    sa.Column('receive_filtered_output', sa.Boolean(), nullable=False),
    sa.Column('chat_alias', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('is_default_target', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('robot_id', 'item_id')
    )
    op.create_index(op.f('ix_robotitem_item_id'), 'robotitem', ['item_id'], unique=False)
    op.create_index(op.f('ix_robotitem_robot_id'), 'robotitem', ['robot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robotitem_robot_id'), table_name='robotitem')
    op.drop_index(op.f('ix_robotitem_item_id'), table_name='robotitem')
    op.drop_table('robotitem')
    op.drop_index(op.f('ix_itemhandleruser_user_id'), table_name='itemhandleruser')
    op.drop_index(op.f('ix_itemhandleruser_item_handler_id'), table_name='itemhandleruser')
    op.drop_table('itemhandleruser')
    op.drop_index(op.f('ix_itemhandleritem_item_id'), table_name='itemhandleritem')
    op.drop_index(op.f('ix_itemhandleritem_item_handler_id'), table_name='itemhandleritem')
    op.drop_table('itemhandleritem')
    op.drop_index(op.f('ix_itemchatsession_item_id'), table_name='itemchatsession')
    op.drop_table('itemchatsession')
    op.drop_index(op.f('ix_robot_owner_id'), table_name='robot')
    op.drop_table('robot')
    op.drop_index(op.f('ix_itemhandler_owner_id'), table_name='itemhandler')
    op.drop_table('itemhandler')
    op.drop_index(op.f('ix_item_owner_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
