/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSkillsRouteImport } from './routes/_layout/skills'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPluginsRouteImport } from './routes/_layout/plugins'
import { Route as LayoutPluginDevRouteImport } from './routes/_layout/plugin-dev'
import { Route as LayoutMcpServersRouteImport } from './routes/_layout/mcp-servers'
import { Route as LayoutKnowledgeRouteImport } from './routes/_layout/knowledge'
import { Route as LayoutItemHandlersRouteImport } from './routes/_layout/item-handlers'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutItemHandlersIndexRouteImport } from './routes/_layout/item-handlers.index'
import { Route as LayoutItemHandlersItemHandlerIdRouteImport } from './routes/_layout/item-handlers.$itemHandlerId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillsRoute = LayoutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPluginsRoute = LayoutPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPluginDevRoute = LayoutPluginDevRouteImport.update({
  id: '/plugin-dev',
  path: '/plugin-dev',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMcpServersRoute = LayoutMcpServersRouteImport.update({
  id: '/mcp-servers',
  path: '/mcp-servers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeRoute = LayoutKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemHandlersRoute = LayoutItemHandlersRouteImport.update({
  id: '/item-handlers',
  path: '/item-handlers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemHandlersIndexRoute = LayoutItemHandlersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutItemHandlersRoute,
} as any)
const LayoutItemHandlersItemHandlerIdRoute =
  LayoutItemHandlersItemHandlerIdRouteImport.update({
    id: '/$itemHandlerId',
    path: '/$itemHandlerId',
    getParentRoute: () => LayoutItemHandlersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/item-handlers': typeof LayoutItemHandlersRouteWithChildren
  '/knowledge': typeof LayoutKnowledgeRoute
  '/mcp-servers': typeof LayoutMcpServersRoute
  '/plugin-dev': typeof LayoutPluginDevRoute
  '/plugins': typeof LayoutPluginsRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/item-handlers/$itemHandlerId': typeof LayoutItemHandlersItemHandlerIdRoute
  '/item-handlers/': typeof LayoutItemHandlersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/knowledge': typeof LayoutKnowledgeRoute
  '/mcp-servers': typeof LayoutMcpServersRoute
  '/plugin-dev': typeof LayoutPluginDevRoute
  '/plugins': typeof LayoutPluginsRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/': typeof LayoutIndexRoute
  '/item-handlers/$itemHandlerId': typeof LayoutItemHandlersItemHandlerIdRoute
  '/item-handlers': typeof LayoutItemHandlersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/item-handlers': typeof LayoutItemHandlersRouteWithChildren
  '/_layout/knowledge': typeof LayoutKnowledgeRoute
  '/_layout/mcp-servers': typeof LayoutMcpServersRoute
  '/_layout/plugin-dev': typeof LayoutPluginDevRoute
  '/_layout/plugins': typeof LayoutPluginsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/skills': typeof LayoutSkillsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/item-handlers/$itemHandlerId': typeof LayoutItemHandlersItemHandlerIdRoute
  '/_layout/item-handlers/': typeof LayoutItemHandlersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/item-handlers'
    | '/knowledge'
    | '/mcp-servers'
    | '/plugin-dev'
    | '/plugins'
    | '/settings'
    | '/skills'
    | '/item-handlers/$itemHandlerId'
    | '/item-handlers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/knowledge'
    | '/mcp-servers'
    | '/plugin-dev'
    | '/plugins'
    | '/settings'
    | '/skills'
    | '/'
    | '/item-handlers/$itemHandlerId'
    | '/item-handlers'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/item-handlers'
    | '/_layout/knowledge'
    | '/_layout/mcp-servers'
    | '/_layout/plugin-dev'
    | '/_layout/plugins'
    | '/_layout/settings'
    | '/_layout/skills'
    | '/_layout/'
    | '/_layout/item-handlers/$itemHandlerId'
    | '/_layout/item-handlers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skills': {
      id: '/_layout/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof LayoutSkillsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plugins': {
      id: '/_layout/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof LayoutPluginsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plugin-dev': {
      id: '/_layout/plugin-dev'
      path: '/plugin-dev'
      fullPath: '/plugin-dev'
      preLoaderRoute: typeof LayoutPluginDevRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mcp-servers': {
      id: '/_layout/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/mcp-servers'
      preLoaderRoute: typeof LayoutMcpServersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge': {
      id: '/_layout/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof LayoutKnowledgeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/item-handlers': {
      id: '/_layout/item-handlers'
      path: '/item-handlers'
      fullPath: '/item-handlers'
      preLoaderRoute: typeof LayoutItemHandlersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/item-handlers/': {
      id: '/_layout/item-handlers/'
      path: '/'
      fullPath: '/item-handlers/'
      preLoaderRoute: typeof LayoutItemHandlersIndexRouteImport
      parentRoute: typeof LayoutItemHandlersRoute
    }
    '/_layout/item-handlers/$itemHandlerId': {
      id: '/_layout/item-handlers/$itemHandlerId'
      path: '/$itemHandlerId'
      fullPath: '/item-handlers/$itemHandlerId'
      preLoaderRoute: typeof LayoutItemHandlersItemHandlerIdRouteImport
      parentRoute: typeof LayoutItemHandlersRoute
    }
  }
}

interface LayoutItemHandlersRouteChildren {
  LayoutItemHandlersItemHandlerIdRoute: typeof LayoutItemHandlersItemHandlerIdRoute
  LayoutItemHandlersIndexRoute: typeof LayoutItemHandlersIndexRoute
}

const LayoutItemHandlersRouteChildren: LayoutItemHandlersRouteChildren = {
  LayoutItemHandlersItemHandlerIdRoute: LayoutItemHandlersItemHandlerIdRoute,
  LayoutItemHandlersIndexRoute: LayoutItemHandlersIndexRoute,
}

const LayoutItemHandlersRouteWithChildren =
  LayoutItemHandlersRoute._addFileChildren(LayoutItemHandlersRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemHandlersRoute: typeof LayoutItemHandlersRouteWithChildren
  LayoutKnowledgeRoute: typeof LayoutKnowledgeRoute
  LayoutMcpServersRoute: typeof LayoutMcpServersRoute
  LayoutPluginDevRoute: typeof LayoutPluginDevRoute
  LayoutPluginsRoute: typeof LayoutPluginsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSkillsRoute: typeof LayoutSkillsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemHandlersRoute: LayoutItemHandlersRouteWithChildren,
  LayoutKnowledgeRoute: LayoutKnowledgeRoute,
  LayoutMcpServersRoute: LayoutMcpServersRoute,
  LayoutPluginDevRoute: LayoutPluginDevRoute,
  LayoutPluginsRoute: LayoutPluginsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSkillsRoute: LayoutSkillsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
